#include "KargaTarayici/UI/ScannerWindow.h"
#include "KargaTarayici/Rules/JsonRuleParser.h"
#include <imgui.h>
#include <filesystem>
#include <sstream>
#include <format>

namespace KargaTarayici::UI {

ScannerWindow::ScannerWindow() {
    RefreshRuleFiles();
    LoadSelectedRules();
}

void ScannerWindow::RefreshRuleFiles() {
    ruleFiles_.clear();
    std::string configDir = "config";
    if (std::filesystem::exists(configDir)) {
        for (const auto& entry : std::filesystem::directory_iterator(configDir)) {
            if (entry.path().extension() == ".json") {
                ruleFiles_.push_back(entry.path().string());
            }
        }
    }
    if (ruleFiles_.empty()) {
        ruleFiles_.push_back("config/default_rules.json");
    }
}

void ScannerWindow::LoadSelectedRules() {
    if (selectedRuleIndex_ >= 0 && selectedRuleIndex_ < static_cast<int>(ruleFiles_.size())) {
        currentRules_ = Rules::JsonRuleParser::ParseFile(ruleFiles_[selectedRuleIndex_]);
    }
}

void ScannerWindow::SetScanResults(const std::vector<Strategies::ScanResult>& results) {
    scanResults_.clear();
    scanExecuted_ = true;

    for (const auto& rule : currentRules_) {
        DiscoveredSymbolItem item{};
        item.symbol = rule.targetSymbol;
        item.moduleName = rule.name;
        item.found = false;
        item.address = 0;

        for (const auto& res : results) {
            if (res.symbol == rule.targetSymbol) {
                item.address = res.foundAddress;
                item.found = res.success;
                break;
            }
        }
        scanResults_.push_back(item);
    }

    GenerateCppHeaderOutput();
}

void ScannerWindow::GenerateCppHeaderOutput() {
    std::stringstream ss;
    ss << "// ===================================================\n";
    ss << "// Generated by Karga Tarayici Scanner Engine\n";
    ss << "// C++ Offsets & Function Pointers Header\n";
    ss << "// ===================================================\n\n";
    ss << "#pragma once\n\n";
    ss << "#include <cstdint>\n\n";
    ss << "namespace GameOffsets {\n\n";

    for (const auto& item : scanResults_) {
        if (item.found) {
            ss << std::format("    constexpr uintptr_t {} = 0x{:08X};\n", item.symbol, item.address);
        } else {
            ss << std::format("    // constexpr uintptr_t {} = 0x00000000; // NOT FOUND / NULLPTR\n", item.symbol);
        }
    }

    ss << "\n} // namespace GameOffsets\n";
    generatedCppHeader_ = ss.str();
}

void ScannerWindow::Render() {
    ImGui::Begin("Karga Scanner Control & Results");

    ImGui::TextColored(ImVec4(0.4f, 0.8f, 1.0f, 1.0f), "Rule Preset Selector:");
    if (!ruleFiles_.empty()) {
        std::vector<const char*> items;
        for (const auto& file : ruleFiles_) {
            items.push_back(file.c_str());
        }
        if (ImGui::Combo("##PresetCombo", &selectedRuleIndex_, items.data(), static_cast<int>(items.size()))) {
            LoadSelectedRules();
        }
    }

    ImGui::SameLine();
    if (ImGui::Button("Refresh Presets")) {
        RefreshRuleFiles();
        LoadSelectedRules();
    }

    ImGui::Separator();
    ImGui::Text("Loaded Rules: %d", static_cast<int>(currentRules_.size()));

    if (ImGui::BeginTabBar("ScannerMainTabs")) {
        if (ImGui::BeginTabItem("Results & Module Tree")) {
            if (scanResults_.empty()) {
                ImGui::TextDisabled("No scan results. Click 'Start Scan' to begin.");
            } else {
                if (ImGui::TreeNodeEx("Discovered Symbols", ImGuiTreeNodeFlags_DefaultOpen)) {
                    for (const auto& item : scanResults_) {
                        if (item.found) {
                            std::string label = std::format("[FOUND] {} -> 0x{:08X}", item.symbol, item.address);
                            if (ImGui::Selectable(label.c_str(), selectedItem_.symbol == item.symbol)) {
                                selectedItem_ = item;
                                hasSelection_ = true;
                            }
                        } else {
                            std::string label = std::format("[NOT FOUND] {} -> 0x00000000", item.symbol);
                            ImGui::TextColored(ImVec4(0.6f, 0.6f, 0.6f, 1.0f), "%s", label.c_str());
                        }
                    }
                    ImGui::TreePop();
                }
            }
            ImGui::EndTabItem();
        }

        if (ImGui::BeginTabItem("C++ Output Header")) {
            if (generatedCppHeader_.empty()) {
                ImGui::TextDisabled("C++ header will be generated after scanning.");
            } else {
                if (ImGui::Button("Copy C++ Header to Clipboard")) {
                    ImGui::SetClipboardText(generatedCppHeader_.c_str());
                }
                ImGui::Separator();
                ImGui::InputTextMultiline("##CppHeaderOutput", const_cast<char*>(generatedCppHeader_.c_str()), 
                                          generatedCppHeader_.size() + 1, ImVec2(-1, -1), ImGuiInputTextFlags_ReadOnly);
            }
            ImGui::EndTabItem();
        }

        ImGui::EndTabBar();
    }

    ImGui::End();
}

}
