#include <gtest/gtest.h>
#include "KargaTarayici/Rules/JsonRuleParser.h"
#include "KargaTarayici/Rules/RuleModel.h"

TEST(JsonRuleParserTest, ParsesAutoGeneratedJsonRules) {
    using namespace KargaTarayici;

    const std::string mockJson = R"([
      {
        "wrapper_name": "netSendPartyExitPacket",
        "param_signature": ["int"],
        "targets": [
          {
            "class_name": "IAbstractPlayer",
            "method_name": "GetMainCharacterIndex",
            "arg_count": 0
          },
          {
            "class_name": "CPythonNetworkStream",
            "method_name": "SendPartyRemovePacket",
            "arg_count": 1
          }
        ]
      }
    ])";

    auto rules = Rules::JsonRuleParser::ParseString(mockJson);
    ASSERT_FALSE(rules.empty());
}
